name: 'First Workflow'
on:
    workflow_dispatch:
    issues:
        types: [opened]

env:
  DAY_OF_WEEK: 'Monday'

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            -   name: Step 1
                run: echo "Step 1 completed! on $DAY_OF_WEEK"
            -   name: Step 2
                run: echo "Step 2 completed! on $DAY_OF_WEEK"
    job2:
        runs-on: ubuntu-latest
        steps:
            -    name: Cowsays
                 uses: mscoutermarsh/cowsays-action@v1
                 with:
            # What does the cow say?
            # optional, default is Ship it!!!!!
                    text: "Ship it on $DAY_OF_WEEK!"    
            # Color of your cow
                    color: red
