name: First Workflow

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Run a one-line script
          run: echo Hello, world!

    job2:
        runs-on: ubuntu-latest

        steps:
        - name: Cowsays
          uses: jessfraz/cowsay-action@master
          with:
            text: "Ready for prod–ship it!"
            color: magenta
